name: Publish

on:
  release:
    types: [created]

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Publish to GitHub packages and Maven Central
        run: ./gradlew publishAllPublicationsToCentralPortal
        env:
          USERNAME: ${{ secrets.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_USER }}
          MAVEN_CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PWD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}



